Name: CI

on:
  push:
    branches:
      - "**"
  pull_request:

jobs:
  lint_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install system packages (for PyQt5/VTK headless)
        run: |
          sudo apt-get update
          sudo apt-get install -y libgl1 libxkbcommon-x11-0 libxcb-render0 libxcb-shape0 libxcb-xfixes0

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install uv
        run: pip install uv

      - name: Create venv and install dependencies (dev)
        run: |
          uv venv
          source .venv/bin/activate
          uv pip install -e ".[dev]"

      - name: Pre-commit (lint/format/type on all files)
        run: |
          source .venv/bin/activate
          pre-commit run --all-files

      - name: Type check (mypy)
        run: |
          source .venv/bin/activate
          mypy polyclash

      - name: Run tests
        run: |
          source .venv/bin/activate
          pytest -q
